// Authoritative NEW STELLANTIS Segment (IHS) master supplied by the user.
// This file is classification only: it maps Segment -> Brand -> Model.
// It does not contain sales volumes.

export const SEGMENT_MODEL_MASTER = [
  ["A-SUV","Tata","Punch"],
  ["B-SUV (<4m)","Tata","Nexon"],
  ["C-MPV","MARUTI SUZUKI","Ertiga"],
  ["A-MPV","MARUTI SUZUKI","Wagon R"],
  ["B-Hatch","MARUTI SUZUKI","Swift"],
  ["B-Hatch","MARUTI SUZUKI","Baleno"],
  ["B-SUV (<4m)","MARUTI SUZUKI","Fronx"],
  ["B-SUV","Hyundai","Creta"],
  ["C-SUV","Mahindra","Scorpio"],
  ["B-SUV (<4m)","MARUTI SUZUKI","Brezza"],
  ["B-SUV","MARUTI SUZUKI","Victoris"],
  ["B-MPV","MARUTI SUZUKI","Eeco"],
  ["B-SUV (<4m)","Hyundai","Venue"],
  ["B-SUV","Kia","Seltos"],
  ["B-SUV (<4m)","Mahindra","Thar"],
  ["A-Hatch","MARUTI SUZUKI","Alto"],
  ["B-SUV (<4m)","Kia","Sonet"],
  ["B-SUV (<4m)","Mahindra","Bolero"],
  ["C-SUV","Mahindra","XUV7XO"],
  ["B-SUV (<4m)","Mahindra","XUV 300, 3XO"],
  ["B-SUV","Toyota","UC HyRyder"],
  ["B-SUV","Tata","Sierra"],
  ["A-Hatch","Tata","Tiago"],
  ["A-SUV","Hyundai","Exter"],
  ["B-SUV","MARUTI SUZUKI","Grand Vitara"],
  ["C-SUV","Mahindra","XEV 9e"],
  ["B-Sedan (<4m)","Hyundai","Xcent / Aura"],
  ["D-MPV","Toyota","Hycross"],
  ["C-MPV","Kia","Carens"],
  ["B-Hatch","Hyundai","i20"],
  ["B-Hatch","Hyundai","i10 Grand"],
  ["B-SUV (<4m)","Skoda","Kylaq"],
  ["C-MPV","MARUTI SUZUKI","XL6"],
  ["B-SUV (<4m)","MG","Windsor"],
  ["B-Sedan (<4m)","Honda","Amaze"],
  ["D-MPV","Toyota","Innova"],
  ["C-SUV","Tata","Harrier"],
  ["D-SUV","Toyota","Fortuner"],
  ["B-Hatch","Toyota","Glanza"],
  ["B-Hatch","Tata","Altroz"],
  ["B-SUV (<4m)","TOYOTA","Taisor"],
  ["C-MPV","Toyota","Rumion"],
  ["A-Hatch","MARUTI SUZUKI","Celerio"],
  ["B-MPV","Renault","Triber"],
  ["B-SUV","Tata","Curvv"],
  ["B-SUV (<4m)","Nissan","Magnite"],
  ["A-SUV","MARUTI SUZUKI","S-Presso"],
  ["C-SUV","Tata","Safari"],
  ["B-SUV","Honda","Elevate"],
  ["B-SUV","MG","ZS EV"],
  ["B-Sedan","Volkswagen","Virtus"],
  ["B-SUV","MARUTI SUZUKI","E-Vitara"],
  ["B-MPV","Nissan","Gravite"],
  ["C-SUV","MG","Hector"],
  ["B-SUV","Skoda","Kushaq"],
  ["B-Sedan","Skoda","Slavia"],
  ["B-SUV","Volkswagen","Taigun"],
  ["B-SUV (<4m)","Kia","Syros"],
  ["B-Sedan (<4m)","Tata","Tigor"],
  ["B-SUV","Renault","Duster"],
  ["C-SUV","Hyundai","Alcazar"],
  ["B-Sedan","Hyundai","Verna"],
  ["B-SUV (<4m)","Renault","Kiger"],
  ["B-Hatch","Citroen","C3"],
  ["B-Sedan","Honda","City"],
  ["A-SUV","MARUTI SUZUKI","Ignis"],
  ["B-SUV (<4m)","MARUTI SUZUKI","Jimny"],
  ["D-MPV","VinFast","Limo Green"],
  ["A-SUV","Renault","Kwid"],
  ["E-Cp/Cb","Mercedes","E Class"],
  ["D-SUV","MG","Majestor"],
  ["B-SUV","Nissan","Tekton"],
  ["D-MPV","MARUTI SUZUKI","Invicto"],
  ["D-Sedan","BMW","3 Series + GT"],
  ["E-Sedan","BMW","5 Series + GT"],
  ["D-SUV","Kia","Sorento"],
  ["C-SUV","BMW","X1"],
  ["C-SUV","BYD","Sealion 7"],
  ["F-SUV","Mercedes","GLS"],
  ["D-SUV","Land Rover","Defender"],
  ["D-Sedan","Toyota","Camry"],
  ["C-SUV","VinFast","VF 7"],
  ["D-SUV","Mercedes","GLC"],
  ["B-SUV","MG","Astor"],
  ["C-SUV","BYD","BYD Atto 3"],
  ["C-SUV","Volkswagen","Tiguan"],
  ["E-SUV","Mercedes","GLE"],
  ["C-SUV","Mercedes","GLA"],
  ["E-SUV","BMW","X5"],
  ["D-SUV","BMW","X3"],
  ["D-Sedan","Mercedes","C Class + CLA"],
  ["E-MPV","Toyota","Vellfire"],
  ["C-SUV","Audi","Q3"],
  ["C-SUV","Skoda","Kodiaq"],
  ["C-SUV","FCA","Compass"],
  ["F-SUV","Land Rover","Range Rover"],
  ["F-SUV","BMW","X7"],
  ["B-SUV","VinFast","VF 6"],
  ["D-SUV","FCA","Meridian"],
  ["B-SUV","Toyota","Ebella"],
  ["D-SUV","Mercedes","EQC/EQS/EQB"],
  ["E-SUV","Land Rover","Range Rover Sports"],
  ["E-MPV","Kia","Carnival"],
  ["B-SUV (<4m)","Mahindra","XUV 400"],
  ["B-SUV","Citroen","C3 Aircross"],
  ["D-MPV","BYD","BYD eMax 7"],
  ["D-SUV","Volvo","XC 60"],
  ["D-Sedan","Audi","A4"],
  ["D-SUV","Volkswagen","Tayron"],
  ["B-SUV","Citroen","Basalt"],
  ["C-Cp/Cb","BMW","2 Series"],
  ["D-SUV","Audi","Q5"],
  ["B-Hatch","Citroen","EC3"],
  ["B-Hatch","Mini","Mini"],
  ["C-Sedan","Mercedes","CLA"],
  ["F-Sedan","Mercedes","S Class"],
  ["E-SUV","Volvo","XC90"],
  ["E-Sedan","Audi","A6"],
  ["C-Hatch","Mercedes","A Class"],
  ["D-SUV","Land Rover","Velar"],
  ["B-SUV","Mini","Countryman/Clubman"],
  ["D-SUV","FCA","Wrangler"],
  ["F-Sedan","BMW","7 Series"],
  ["E-SUV","Audi","Q7"],
  ["C-Cp/Cb","Porsche","Cayman"],
  ["C-SUV","Volvo","EX30"],
  ["C-Cp/Cb","Porsche","Porsche"],
];

export const SEGMENT_MODEL_ROWS = SEGMENT_MODEL_MASTER.map(([segment, brand, model]) => ({
  segment,
  brand,
  model,
}));

export function getModelsForSegment(segment) {
  return SEGMENT_MODEL_ROWS.filter((row) => row.segment === segment);
}
