-- Lightweight Industry intelligence: month-wise segment totals only.
CREATE TABLE IF NOT EXISTS public.industry_segment_monthly (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sales_month DATE NOT NULL,
  segment TEXT NOT NULL,
  bodyshape TEXT,
  units INTEGER NOT NULL DEFAULT 0 CHECK (units >= 0),
  source_workbook TEXT NOT NULL DEFAULT 'India TIV Sep26.xlsx',
  source_sheet TEXT NOT NULL DEFAULT '2026 Sep',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (sales_month, segment, bodyshape)
);

CREATE INDEX IF NOT EXISTS industry_segment_monthly_month_idx
  ON public.industry_segment_monthly (sales_month);

CREATE INDEX IF NOT EXISTS industry_segment_monthly_segment_idx
  ON public.industry_segment_monthly (segment);

ALTER TABLE public.industry_segment_monthly DISABLE ROW LEVEL SECURITY;