create table if not exists public.industry_segment_master_v2 (
  id bigint generated by default as identity primary key,
  segment text not null,
  brand text not null,
  model_name text not null,
  source text not null default 'user_segment_master',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (segment, brand, model_name)
);

create table if not exists public.industry_segment_history_v2 (
  id bigint generated by default as identity primary key,
  sales_period date not null,
  segment text not null,
  units integer not null default 0,
  period_type text not null check (period_type in ('ANNUAL','MONTHLY')),
  source_workbook text not null,
  source_sheet text not null,
  created_at timestamptz not null default now(),
  unique (sales_period, segment)
);

create table if not exists public.industry_manufacturer_history_v2 (
  id bigint generated by default as identity primary key,
  sales_period date not null,
  manufacturer text not null,
  units integer not null default 0,
  period_type text not null check (period_type in ('ANNUAL','MONTHLY')),
  record_type text not null check (record_type in ('MANUFACTURER','TOTAL')),
  source_workbook text not null,
  source_sheet text not null,
  created_at timestamptz not null default now(),
  unique (sales_period, manufacturer, record_type)
);

create index if not exists industry_segment_history_v2_period_idx on public.industry_segment_history_v2 (sales_period);
create index if not exists industry_segment_history_v2_segment_idx on public.industry_segment_history_v2 (segment);
create index if not exists industry_manufacturer_history_v2_period_idx on public.industry_manufacturer_history_v2 (sales_period);
create index if not exists industry_manufacturer_history_v2_manufacturer_idx on public.industry_manufacturer_history_v2 (manufacturer);

comment on table public.industry_segment_master_v2 is 'Definitive Segment > Brand > Model classification supplied by business owner.';
comment on table public.industry_segment_history_v2 is 'Historical industry TIV by segment from IND.xlsx. 1991-1996 annual; 1997 onward monthly.';
comment on table public.industry_manufacturer_history_v2 is 'Historical manufacturer movement from comp.xlsx. 1991-1996 annual; 1997 onward monthly. Source manufacturer names preserved.';
