create table if not exists public.sales_cockpit_brand_monthly_bookings (
  id bigint generated by default as identity primary key,
  brand text not null check (brand in ('Jeep', 'Citroën')),
  sales_year integer not null check (sales_year between 2000 and 2100),
  sales_month integer not null check (sales_month between 1 and 12),
  units integer not null check (units >= 0),
  source text not null default 'User supplied monthly bookings',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand, sales_year, sales_month)
);
alter table public.sales_cockpit_brand_monthly_bookings enable row level security;
grant select, insert, update, delete on public.sales_cockpit_brand_monthly_bookings to anon, authenticated;
drop policy if exists "Allow public read brand monthly bookings" on public.sales_cockpit_brand_monthly_bookings;
create policy "Allow public read brand monthly bookings" on public.sales_cockpit_brand_monthly_bookings for select to anon, authenticated using (true);
drop policy if exists "Allow public insert brand monthly bookings" on public.sales_cockpit_brand_monthly_bookings;
create policy "Allow public insert brand monthly bookings" on public.sales_cockpit_brand_monthly_bookings for insert to anon, authenticated with check (true);
drop policy if exists "Allow public update brand monthly bookings" on public.sales_cockpit_brand_monthly_bookings;
create policy "Allow public update brand monthly bookings" on public.sales_cockpit_brand_monthly_bookings for update to anon, authenticated using (true) with check (true);
drop policy if exists "Allow public delete brand monthly bookings" on public.sales_cockpit_brand_monthly_bookings;
create policy "Allow public delete brand monthly bookings" on public.sales_cockpit_brand_monthly_bookings for delete to anon, authenticated using (true);
grant usage, select on sequence public.sales_cockpit_brand_monthly_bookings_id_seq to anon, authenticated;
