-- Industry intelligence foundation.
-- The workbook is treated as source material; summary/subtotal rows are not stored.

CREATE TABLE IF NOT EXISTS public.industry_model_master (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_workbook TEXT NOT NULL DEFAULT 'India TIV Sep26.xlsx',
  source_sheet TEXT NOT NULL DEFAULT 'Master-Sep26',
  source_row INTEGER,
  brand TEXT NOT NULL,
  model_name TEXT NOT NULL,
  old_segment TEXT,
  stellantis_segment TEXT,
  ihs_segment TEXT,
  validation_status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (validation_status IN ('PENDING','VALIDATED','REVIEW')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS industry_model_master_brand_idx
  ON public.industry_model_master (brand);
CREATE INDEX IF NOT EXISTS industry_model_master_stellantis_segment_idx
  ON public.industry_model_master (stellantis_segment);
CREATE INDEX IF NOT EXISTS industry_model_master_ihs_segment_idx
  ON public.industry_model_master (ihs_segment);

CREATE TABLE IF NOT EXISTS public.industry_model_monthly (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id BIGINT NOT NULL REFERENCES public.industry_model_master(id) ON DELETE CASCADE,
  sales_month DATE NOT NULL,
  units INTEGER NOT NULL DEFAULT 0 CHECK (units >= 0),
  source_workbook TEXT NOT NULL DEFAULT 'India TIV Sep26.xlsx',
  source_sheet TEXT NOT NULL DEFAULT 'Master-Sep26',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (model_id, sales_month)
);

CREATE INDEX IF NOT EXISTS industry_model_monthly_month_idx
  ON public.industry_model_monthly (sales_month);
CREATE INDEX IF NOT EXISTS industry_model_monthly_model_month_idx
  ON public.industry_model_monthly (model_id, sales_month);

-- Keep the current project's access model consistent while the Industry import workflow is built.
ALTER TABLE public.industry_model_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.industry_model_monthly DISABLE ROW LEVEL SECURITY;
